"""Ajout commande_vente_id à UniteProduit

Revision ID: 01cfbbc9787e
Revises: 48b32c5b2546
Create Date: 2025-05-27 12:48:54.593656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cfbbc9787e'
down_revision: Union[str, None] = '48b32c5b2546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unites_produit', sa.Column('commande_vente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unites_produit', 'commandes_ventes', ['commande_vente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unites_produit', type_='foreignkey')
    op.drop_column('unites_produit', 'commande_vente_id')
    # ### end Alembic commands ###
