"""create rapports table

Revision ID: 163a4ed76ebb
Revises: 96cd5c00cd56
Create Date: 2025-05-12 16:26:51.262826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '163a4ed76ebb'
down_revision: Union[str, None] = '96cd5c00cd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unites_tracabilite', table_name='unites_produit')
    op.drop_table('unites_produit')
    op.drop_table('rapports')
    op.drop_index('idx_factures_client_id', table_name='factures')
    op.drop_constraint('fk_factures_client_id', 'factures', type_='foreignkey')
    op.alter_column('interventions', 'produit_ex',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interventions', 'produit_ex',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key('fk_factures_client_id', 'factures', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_factures_client_id', 'factures', ['client_id'], unique=False)
    op.create_table('rapports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contenu', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_creation', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], name='fk_sub_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], name='rapports_sub_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rapports_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='rapports_pkey')
    )
    op.create_table('unites_produit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracabilite', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(length=50), server_default=sa.text("'disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name='fk_produit', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='unites_produit_pkey'),
    sa.UniqueConstraint('tracabilite', name='unites_produit_tracabilite_key')
    )
    op.create_index('idx_unites_tracabilite', 'unites_produit', ['tracabilite'], unique=False)
    # ### end Alembic commands ###
