"""add created_by to Produit

Revision ID: 2027075f616a
Revises: a84af24282c7
Create Date: 2025-05-05 00:47:15.240796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2027075f616a'
down_revision: Union[str, None] = 'a84af24282c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produits', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produits', type_='foreignkey')
    op.drop_column('produits', 'created_by')
    # ### end Alembic commands ###
