"""create client_produits table

Revision ID: 2e44bcb47528
Revises: e8adce3bce14
Create Date: 2025-05-29 17:47:36.100270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e44bcb47528'
down_revision: Union[str, None] = 'e8adce3bce14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('nom_produit', sa.String(), nullable=True),
    sa.Column('categorie_produit', sa.String(), nullable=True),
    sa.Column('prix_unitaire_backup', sa.Float(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('date_achat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_ventes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_produits_id'), 'client_produits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_produits_id'), table_name='client_produits')
    op.drop_table('client_produits')
    # ### end Alembic commands ###
