"""Add parent_user_id to Historique

Revision ID: 4164d9110c0d
Revises: 6c458683de82
Create Date: 2025-05-09 09:04:32.889591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4164d9110c0d'
down_revision: Union[str, None] = '6c458683de82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'historiques', 'users', ['parent_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historiques', type_='foreignkey')
    op.drop_column('historiques', 'parent_user_id')
    # ### end Alembic commands ###
