"""Ajout adresse  utilisateur

Revision ID: 48b32c5b2546
Revises: 4ecea6a27dc7
Create Date: 2025-05-27 11:59:05.699735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b32c5b2546'
down_revision: Union[str, None] = '4ecea6a27dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('addresse', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'addresse')
    # ### end Alembic commands ###
