"""ajout table galerie_photo

Revision ID: 48e570c06634
Revises: 543287b897b8
Create Date: 2025-05-26 02:35:51.595763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e570c06634'
down_revision: Union[str, None] = '543287b897b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galerie_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galerie_photos_id'), 'galerie_photos', ['id'], unique=False)
    op.drop_constraint('interventions_user_id_fkey', 'interventions', type_='foreignkey')
    op.create_foreign_key(None, 'interventions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    op.drop_constraint('reset_tokens_user_id_fkey', 'reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'reset_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reset_tokens', type_='foreignkey')
    op.create_foreign_key('reset_tokens_user_id_fkey', 'reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_constraint(None, 'interventions', type_='foreignkey')
    op.create_foreign_key('interventions_user_id_fkey', 'interventions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_galerie_photos_id'), table_name='galerie_photos')
    op.drop_table('galerie_photos')
    # ### end Alembic commands ###
