"""Ajout sub_user_id à Facture

Revision ID: 4ecea6a27dc7
Revises: e9c17e9e78a0
Create Date: 2025-05-27 11:34:17.155675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecea6a27dc7'
down_revision: Union[str, None] = 'e9c17e9e78a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('sub_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factures', 'sub_users', ['sub_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factures', type_='foreignkey')
    op.drop_column('factures', 'sub_user_id')
    # ### end Alembic commands ###
