"""add stock_min to produits

Revision ID: 523eabb7bc90
Revises: 3a9223087095
Create Date: 2025-04-24 13:13:31.351142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523eabb7bc90'
down_revision: Union[str, None] = '3a9223087095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('stock_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'stock_min')
    # ### end Alembic commands ###
