"""Ajout societe_ou_entreprise dans users

Revision ID: 5ce14231c3bb
Revises: 3765c94a6195
Create Date: 2025-04-26 02:26:06.404040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce14231c3bb'
down_revision: Union[str, None] = '3765c94a6195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('societe_ou_entreprise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'societe_ou_entreprise')
    # ### end Alembic commands ###
