"""Ajout colonne société_ou_entreprise users

Revision ID: 5cf6dede8601
Revises: a1d449f1975b
Create Date: 2025-04-26 02:18:37.846957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf6dede8601'
down_revision: Union[str, None] = 'a1d449f1975b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_users', sa.Column('société_ou_entreprise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_users', 'société_ou_entreprise')
    # ### end Alembic commands ###
