"""add code_barre to produit

Revision ID: 5e2b063e93bc
Revises: f6d08d901081
Create Date: 2025-05-15 16:26:29.808860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2b063e93bc'
down_revision: Union[str, None] = 'f6d08d901081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('code_barre', sa.String(), nullable=True))
    op.create_index(op.f('ix_produits_code_barre'), 'produits', ['code_barre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produits_code_barre'), table_name='produits')
    op.drop_column('produits', 'code_barre')
    # ### end Alembic commands ###
