"""Ajout user_id dans les modèles

Revision ID: 66133bb8d19b
Revises: 5638eaf20242
Create Date: 2025-05-03 03:13:02.938936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66133bb8d19b'
down_revision: Union[str, None] = '5638eaf20242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.add_column('commandes_achats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commandes_achats', 'users', ['user_id'], ['id'])
    op.add_column('commandes_ventes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commandes_ventes', 'users', ['user_id'], ['id'])
    op.add_column('depenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'depenses', 'users', ['user_id'], ['id'])
    op.add_column('factures', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factures', 'users', ['user_id'], ['id'])
    op.add_column('fournisseurs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fournisseurs', 'users', ['user_id'], ['id'])
    op.add_column('interventions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interventions', 'users', ['user_id'], ['id'])
    op.add_column('lignes_commandes_achats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lignes_commandes_achats', 'users', ['user_id'], ['id'])
    op.add_column('lignes_commandes_ventes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lignes_commandes_ventes', 'users', ['user_id'], ['id'])
    op.add_column('lignes_facture', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lignes_facture', 'users', ['user_id'], ['id'])
    op.add_column('paiements', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paiements', 'users', ['user_id'], ['id'])
    op.add_column('produits', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produits', type_='foreignkey')
    op.drop_column('produits', 'user_id')
    op.drop_constraint(None, 'paiements', type_='foreignkey')
    op.drop_column('paiements', 'user_id')
    op.drop_constraint(None, 'lignes_facture', type_='foreignkey')
    op.drop_column('lignes_facture', 'user_id')
    op.drop_constraint(None, 'lignes_commandes_ventes', type_='foreignkey')
    op.drop_column('lignes_commandes_ventes', 'user_id')
    op.drop_constraint(None, 'lignes_commandes_achats', type_='foreignkey')
    op.drop_column('lignes_commandes_achats', 'user_id')
    op.drop_constraint(None, 'interventions', type_='foreignkey')
    op.drop_column('interventions', 'user_id')
    op.drop_constraint(None, 'fournisseurs', type_='foreignkey')
    op.drop_column('fournisseurs', 'user_id')
    op.drop_constraint(None, 'factures', type_='foreignkey')
    op.drop_column('factures', 'user_id')
    op.drop_constraint(None, 'depenses', type_='foreignkey')
    op.drop_column('depenses', 'user_id')
    op.drop_constraint(None, 'commandes_ventes', type_='foreignkey')
    op.drop_column('commandes_ventes', 'user_id')
    op.drop_constraint(None, 'commandes_achats', type_='foreignkey')
    op.drop_column('commandes_achats', 'user_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
