"""add avatar_url, bio, created_at to users and sub_users

Revision ID: 6833cba99527
Revises: e5940e946022
Create Date: 2025-04-23 21:44:54.424409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6833cba99527'
down_revision: Union[str, None] = 'e5940e946022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('sub_users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('sub_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('sub_users', 'created_at')
    op.drop_column('sub_users', 'bio')
    op.drop_column('sub_users', 'avatar_url')
    # ### end Alembic commands ###
