"""initial supabase setup

Revision ID: 690b15557b5c
Revises: 
Create Date: 2025-05-28 11:30:40.745250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690b15557b5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_main_user', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('societe_ou_entreprise', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('logo_entreprise', sa.String(), nullable=True),
    sa.Column('addresse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('entreprise', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('date_depense', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_id'), 'depenses', ['id'], unique=False)
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('type_fourniture', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fournisseurs_id'), 'fournisseurs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('sub_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('parent_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_users_id'), 'sub_users', ['id'], unique=False)
    op.create_table('commandes_achats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('date_commande', sa.DateTime(), nullable=True),
    sa.Column('total_ht', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('tva_appliquee', sa.Boolean(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_achats_id'), 'commandes_achats', ['id'], unique=False)
    op.create_table('commandes_ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_commande', sa.DateTime(), nullable=True),
    sa.Column('total_ht', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('tva_appliquee', sa.Boolean(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_ventes_id'), 'commandes_ventes', ['id'], unique=False)
    op.create_table('historiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('type_entite', sa.String(), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.Column('nom_user', sa.String(), nullable=True),
    sa.Column('nom_sub_user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiques_id'), 'historiques', ['id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_intervention', sa.DateTime(), nullable=True),
    sa.Column('produit_ex', sa.String(), nullable=True),
    sa.Column('caracteristique_ex', sa.Text(), nullable=True),
    sa.Column('commentaire_ex', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=False),
    sa.Column('prix_achat', sa.Float(), nullable=False),
    sa.Column('prix_vente', sa.Float(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('caracteristiques', sa.Text(), nullable=True),
    sa.Column('couleur', sa.String(), nullable=True),
    sa.Column('etat', sa.String(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('is_installe', sa.Boolean(), nullable=True),
    sa.Column('tracabilite', sa.String(), nullable=True),
    sa.Column('emplacement', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stock_min', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_id'), 'produits', ['id'], unique=False)
    op.create_table('rapports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_rapport', sa.Date(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapports_id'), 'rapports', ['id'], unique=False)
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('achat', 'vente', 'devis', 'proforma', name='typefacture'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('total_ht', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_ventes.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_table('galerie_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galerie_photos_id'), 'galerie_photos', ['id'], unique=False)
    op.create_table('historiques_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiques_interventions_id'), 'historiques_interventions', ['id'], unique=False)
    op.create_table('intervention_produits',
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], )
    )
    op.create_table('lignes_commandes_achats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('total_ligne', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_achats.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_commandes_achats_id'), 'lignes_commandes_achats', ['id'], unique=False)
    op.create_table('lignes_commandes_ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('total_ligne', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes_ventes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_commandes_ventes_id'), 'lignes_commandes_ventes', ['id'], unique=False)
    op.create_table('unites_produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('tracabilite', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('code_barre', sa.String(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('commande_vente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_vente_id'], ['commandes_ventes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unites_produit_code_barre'), 'unites_produit', ['code_barre'], unique=True)
    op.create_index(op.f('ix_unites_produit_id'), 'unites_produit', ['id'], unique=False)
    op.create_index(op.f('ix_unites_produit_tracabilite'), 'unites_produit', ['tracabilite'], unique=True)
    op.create_table('lignes_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('total_ligne', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_facture_id'), 'lignes_facture', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('moyen_paiement', sa.String(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    op.drop_index(op.f('ix_lignes_facture_id'), table_name='lignes_facture')
    op.drop_table('lignes_facture')
    op.drop_index(op.f('ix_unites_produit_tracabilite'), table_name='unites_produit')
    op.drop_index(op.f('ix_unites_produit_id'), table_name='unites_produit')
    op.drop_index(op.f('ix_unites_produit_code_barre'), table_name='unites_produit')
    op.drop_table('unites_produit')
    op.drop_index(op.f('ix_lignes_commandes_ventes_id'), table_name='lignes_commandes_ventes')
    op.drop_table('lignes_commandes_ventes')
    op.drop_index(op.f('ix_lignes_commandes_achats_id'), table_name='lignes_commandes_achats')
    op.drop_table('lignes_commandes_achats')
    op.drop_table('intervention_produits')
    op.drop_index(op.f('ix_historiques_interventions_id'), table_name='historiques_interventions')
    op.drop_table('historiques_interventions')
    op.drop_index(op.f('ix_galerie_photos_id'), table_name='galerie_photos')
    op.drop_table('galerie_photos')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_rapports_id'), table_name='rapports')
    op.drop_table('rapports')
    op.drop_index(op.f('ix_produits_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_historiques_id'), table_name='historiques')
    op.drop_table('historiques')
    op.drop_index(op.f('ix_commandes_ventes_id'), table_name='commandes_ventes')
    op.drop_table('commandes_ventes')
    op.drop_index(op.f('ix_commandes_achats_id'), table_name='commandes_achats')
    op.drop_table('commandes_achats')
    op.drop_index(op.f('ix_sub_users_id'), table_name='sub_users')
    op.drop_table('sub_users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fournisseurs_id'), table_name='fournisseurs')
    op.drop_table('fournisseurs')
    op.drop_index(op.f('ix_depenses_id'), table_name='depenses')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
