"""Add sub_user_id to historique

Revision ID: 6c458683de82
Revises: f2170c305c03
Create Date: 2025-05-06 08:26:02.551331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c458683de82'
down_revision: Union[str, None] = 'f2170c305c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('sub_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'historiques', 'sub_users', ['sub_user_id'], ['id'])
    op.add_column('historiques_interventions', sa.Column('sub_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'historiques_interventions', 'sub_users', ['sub_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historiques_interventions', type_='foreignkey')
    op.drop_column('historiques_interventions', 'sub_user_id')
    op.drop_constraint(None, 'historiques', type_='foreignkey')
    op.drop_column('historiques', 'sub_user_id')
    # ### end Alembic commands ###
