"""Ajout paiements

Revision ID: 76dae3d1e7a5
Revises: 3d7e2ca334bc
Create Date: 2025-04-26 00:16:10.872383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76dae3d1e7a5'
down_revision: Union[str, None] = '3d7e2ca334bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=True),
    sa.Column('moyen_paiement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('commandes_achats', 'date_commande',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('commandes_achats', 'total_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('commandes_achats', 'total_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('commandes_achats', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_commandes_achats_id'), 'commandes_achats', ['id'], unique=False)
    op.alter_column('commandes_ventes', 'date_commande',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('commandes_ventes', 'total_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('commandes_ventes', 'total_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('commandes_ventes', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_commandes_ventes_id'), 'commandes_ventes', ['id'], unique=False)
    op.create_index(op.f('ix_lignes_commandes_achats_id'), 'lignes_commandes_achats', ['id'], unique=False)
    op.create_index(op.f('ix_lignes_commandes_ventes_id'), 'lignes_commandes_ventes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lignes_commandes_ventes_id'), table_name='lignes_commandes_ventes')
    op.drop_index(op.f('ix_lignes_commandes_achats_id'), table_name='lignes_commandes_achats')
    op.drop_index(op.f('ix_commandes_ventes_id'), table_name='commandes_ventes')
    op.alter_column('commandes_ventes', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_ventes', 'total_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_ventes', 'total_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_ventes', 'date_commande',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_commandes_achats_id'), table_name='commandes_achats')
    op.alter_column('commandes_achats', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_achats', 'total_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_achats', 'total_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('commandes_achats', 'date_commande',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('paiements')
    # ### end Alembic commands ###
