"""Fix FK to sub_users

Revision ID: 7768b67e5fc5
Revises: 9301d49f921e
Create Date: 2025-06-11 09:45:19.340410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7768b67e5fc5'
down_revision: Union[str, None] = '9301d49f921e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tutoriels_created_at', table_name='tutoriels')
    op.drop_index('idx_tutoriels_titre', table_name='tutoriels')
    op.create_index(op.f('ix_tutoriels_id'), 'tutoriels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutoriels_id'), table_name='tutoriels')
    op.create_index('idx_tutoriels_titre', 'tutoriels', ['titre'], unique=False)
    op.create_index('idx_tutoriels_created_at', 'tutoriels', ['created_at'], unique=False)
    # ### end Alembic commands ###
