"""Ajout société_ou_entreprise dans users

Revision ID: 7c8ee98cc51c
Revises: 7d842738e2f1
Create Date: 2025-04-26 02:21:51.561634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8ee98cc51c'
down_revision: Union[str, None] = '7d842738e2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_users', 'société_ou_entreprise')
    op.add_column('users', sa.Column('société_ou_entreprise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'société_ou_entreprise')
    op.add_column('sub_users', sa.Column('société_ou_entreprise', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
