"""Ajout champ telephone à User et SubUser

Revision ID: 7defecc76785
Revises: e30b60fb4cd6
Create Date: 2025-05-15 01:02:11.349127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7defecc76785'
down_revision: Union[str, None] = 'e30b60fb4cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_users', sa.Column('telephone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    op.drop_column('sub_users', 'telephone')
    # ### end Alembic commands ###
