"""Ajout colonne devise Facture et Paiement

Revision ID: 82c58791ab44
Revises: 76dae3d1e7a5
Create Date: 2025-04-26 00:30:07.445844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c58791ab44'
down_revision: Union[str, None] = '76dae3d1e7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('devise', sa.String(), nullable=True))
    op.add_column('paiements', sa.Column('devise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paiements', 'devise')
    op.drop_column('factures', 'devise')
    # ### end Alembic commands ###
