"""Ajout commande_id à Facture

Revision ID: 8b34c2a55b43
Revises: 01cfbbc9787e
Create Date: 2025-05-27 13:32:32.816887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b34c2a55b43'
down_revision: Union[str, None] = '01cfbbc9787e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('commande_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factures', 'commandes_ventes', ['commande_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factures', type_='foreignkey')
    op.drop_column('factures', 'commande_id')
    # ### end Alembic commands ###
