"""add relationship produit -> unite_produit

Revision ID: 96cd5c00cd56
Revises: 90dd900327b3
Create Date: 2025-05-09 22:11:21.586730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96cd5c00cd56'
down_revision: Union[str, None] = '90dd900327b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracabilite', table_name='unites_produit')
    op.drop_table('unites_produit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unites_produit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tracabilite', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(length=50), server_default=sa.text("'disponible'::character varying"), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name='unites_produit_produit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='unites_produit_pkey'),
    sa.UniqueConstraint('tracabilite', name='unites_produit_tracabilite_key')
    )
    op.create_index('idx_tracabilite', 'unites_produit', ['tracabilite'], unique=False)
    # ### end Alembic commands ###
