"""add user_id to commandes_ventes

Revision ID: 9cd8aa2e23a5
Revises: ad0f1a94b55b
Create Date: 2025-05-14 03:19:56.290193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd8aa2e23a5'
down_revision: Union[str, None] = 'ad0f1a94b55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
