"""Ajout table Depense

Revision ID: a1d449f1975b
Revises: 0c508db1c40c
Create Date: 2025-04-26 00:43:27.639774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d449f1975b'
down_revision: Union[str, None] = '0c508db1c40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=True),
    sa.Column('date_depense', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_id'), 'depenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depenses_id'), table_name='depenses')
    op.drop_table('depenses')
    # ### end Alembic commands ###
