"""create all tables

Revision ID: a72c41c92a5f
Revises: 7768b67e5fc5
Create Date: 2026-01-21 23:41:51.932982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a72c41c92a5f'
down_revision: Union[str, None] = '7768b67e5fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('granted_by_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_client_followup_id'), 'client_followup', ['id'], unique=False)
    op.alter_column('depot_services', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('depot_services', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_depot_services_id'), 'depot_services', ['id'], unique=False)
    op.alter_column('depot_tarif_item', 'depot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('depot_tarif_item', 'tarif_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('depot_tarif_item', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('depot_tarif_item', 'prix_personnalise',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('depot_tarif_item', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_depot_tarif_item_depot_id'), table_name='depot_tarif_item')
    op.drop_index(op.f('idx_depot_tarif_item_tarif_id'), table_name='depot_tarif_item')
    op.create_index(op.f('ix_depot_tarif_item_id'), 'depot_tarif_item', ['id'], unique=False)
    op.drop_constraint(op.f('depot_tarif_item_tarif_id_fkey'), 'depot_tarif_item', type_='foreignkey')
    op.create_foreign_key(None, 'depot_tarif_item', 'depot_tarifs', ['tarif_id'], ['id'])
    op.alter_column('depot_tarifs', 'tarif_unitaire',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('depot_tarifs', 'tarif_par_minute',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('depot_tarifs', 'date_creation',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_depot_tarifs_id'), 'depot_tarifs', ['id'], unique=False)
    op.drop_constraint(op.f('depot_tarifs_service_id_fkey'), 'depot_tarifs', type_='foreignkey')
    op.create_foreign_key(None, 'depot_tarifs', 'depot_services', ['service_id'], ['id'])
    op.alter_column('depots', 'description_bien',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('depots', 'date_depot',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('depots', 'date_retrait',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('depots', 'prix_personnalise',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('depots', 'prix_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_depots_id'), 'depots', ['id'], unique=False)
    op.drop_constraint(op.f('depots_service_id_fkey'), 'depots', type_='foreignkey')
    op.drop_constraint(op.f('depots_tarif_id_fkey'), 'depots', type_='foreignkey')
    op.create_foreign_key(None, 'depots', 'depot_tarifs', ['tarif_id'], ['id'])
    op.create_foreign_key(None, 'depots', 'depot_services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'depots', 'clients', ['client_id'], ['id'])
    op.create_index(op.f('ix_factures_depot_id'), 'factures_depot', ['id'], unique=False)
    op.alter_column('sub_users', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('sub_users', 'addresse',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'sub_users', ['nif'])
    op.alter_column('users', 'nif',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.18'))
    op.create_unique_constraint(None, 'users', ['nif'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.18'))
    op.alter_column('users', 'nif',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'sub_users', type_='unique')
    op.alter_column('sub_users', 'addresse',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sub_users', 'tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_factures_depot_id'), table_name='factures_depot')
    op.drop_constraint(None, 'depots', type_='foreignkey')
    op.drop_constraint(None, 'depots', type_='foreignkey')
    op.drop_constraint(None, 'depots', type_='foreignkey')
    op.create_foreign_key(op.f('depots_tarif_id_fkey'), 'depots', 'depot_tarifs', ['tarif_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('depots_service_id_fkey'), 'depots', 'depot_services', ['service_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_depots_id'), table_name='depots')
    op.alter_column('depots', 'prix_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('depots', 'prix_personnalise',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('depots', 'date_retrait',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('depots', 'date_depot',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('depots', 'description_bien',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'depot_tarifs', type_='foreignkey')
    op.create_foreign_key(op.f('depot_tarifs_service_id_fkey'), 'depot_tarifs', 'depot_services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_depot_tarifs_id'), table_name='depot_tarifs')
    op.alter_column('depot_tarifs', 'date_creation',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('depot_tarifs', 'tarif_par_minute',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('depot_tarifs', 'tarif_unitaire',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'depot_tarif_item', type_='foreignkey')
    op.create_foreign_key(op.f('depot_tarif_item_tarif_id_fkey'), 'depot_tarif_item', 'depot_tarifs', ['tarif_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_depot_tarif_item_id'), table_name='depot_tarif_item')
    op.create_index(op.f('idx_depot_tarif_item_tarif_id'), 'depot_tarif_item', ['tarif_id'], unique=False)
    op.create_index(op.f('idx_depot_tarif_item_depot_id'), 'depot_tarif_item', ['depot_id'], unique=False)
    op.alter_column('depot_tarif_item', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('depot_tarif_item', 'prix_personnalise',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('depot_tarif_item', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('depot_tarif_item', 'tarif_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('depot_tarif_item', 'depot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_depot_services_id'), table_name='depot_services')
    op.alter_column('depot_services', 'date_creation',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('depot_services', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_client_followup_id'), table_name='client_followup')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
