"""add notifications table

Revision ID: ad0f1a94b55b
Revises: 9451daf8c0f1
Create Date: 2025-05-14 02:12:13.582105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f1a94b55b'
down_revision: Union[str, None] = '9451daf8c0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_rapports_id'), 'rapports', ['id'], unique=False)
    op.drop_constraint('unites_produit_tracabilite_key', 'unites_produit', type_='unique')
    op.create_index(op.f('ix_unites_produit_id'), 'unites_produit', ['id'], unique=False)
    op.create_index(op.f('ix_unites_produit_tracabilite'), 'unites_produit', ['tracabilite'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unites_produit_tracabilite'), table_name='unites_produit')
    op.drop_index(op.f('ix_unites_produit_id'), table_name='unites_produit')
    op.create_unique_constraint('unites_produit_tracabilite_key', 'unites_produit', ['tracabilite'])
    op.drop_index(op.f('ix_rapports_id'), table_name='rapports')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
