"""create factures and lignes_facture tables

Revision ID: ce7989514af6
Revises: 523eabb7bc90
Create Date: 2025-04-24 18:31:01.825959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7989514af6'
down_revision: Union[str, None] = '523eabb7bc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('achat', 'vente', 'devis', 'proforma', name='typefacture'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('total_ht', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_table('lignes_facture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('total_ligne', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_facture_id'), 'lignes_facture', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lignes_facture_id'), table_name='lignes_facture')
    op.drop_table('lignes_facture')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
