"""add commande_achat_id to factures

Revision ID: e0043c9dac31
Revises: 2e44bcb47528
Create Date: 2025-05-29 23:58:13.257582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0043c9dac31'
down_revision: Union[str, None] = '2e44bcb47528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factures', sa.Column('commande_achat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'factures', 'commandes_achats', ['commande_achat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factures', type_='foreignkey')
    op.drop_column('factures', 'commande_achat_id')
    # ### end Alembic commands ###
