"""retry add user_id to commandes_ventes

Revision ID: e30b60fb4cd6
Revises: 9cd8aa2e23a5
Create Date: 2025-05-14 03:22:01.041086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30b60fb4cd6'
down_revision: Union[str, None] = '9cd8aa2e23a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
