"""add parent_user_id to User

Revision ID: e8adce3bce14
Revises: 0c2831256700
Create Date: 2025-05-29 10:07:00.326303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8adce3bce14'
down_revision: Union[str, None] = '0c2831256700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_user_id')
    # ### end Alembic commands ###
