"""Ajout logo entreprise utilisateur

Revision ID: e9c17e9e78a0
Revises: 48e570c06634
Create Date: 2025-05-27 11:11:38.759206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c17e9e78a0'
down_revision: Union[str, None] = '48e570c06634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logo_entreprise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_entreprise')
    # ### end Alembic commands ###
