"""add nom_user and nom_sub_user to historique

Revision ID: f6d08d901081
Revises: 7defecc76785
Create Date: 2025-05-15 09:45:22.270046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d08d901081'
down_revision: Union[str, None] = '7defecc76785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historiques', sa.Column('nom_user', sa.String(), nullable=True))
    op.add_column('historiques', sa.Column('nom_sub_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historiques', 'nom_sub_user')
    op.drop_column('historiques', 'nom_user')
    # ### end Alembic commands ###
