"""Ajout commande_vente_id à UniteProduit

Revision ID: fc99c12b52e2
Revises: 8b34c2a55b43
Create Date: 2025-05-27 14:37:41.661326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc99c12b52e2'
down_revision: Union[str, None] = '8b34c2a55b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
